LOTS OF CHANGES

diff --git a/bin/app b/bin/app
--- a/bin/app
+++ b/bin/app
@@ -1,57 +1,75 @@
 #!/usr/bin/env bash
 
-source $HOME/includes/bashstrap
-include mk
+source $BASHSTRAP
+include sys
+include print
 
-CMDS="list create add remove" # ANY MORE NEEDED?
+CMDS="list create add remove"
 PKGS=$HOME/packages
 
 cmd=${1:-list}
 shift
 
 if ! [[ $CMDS = *$cmd* ]]; then
-	echo "💀 $cmd is not a known command"
-	echo "COMMANDS: $CMDS"
+	print::hr
+	print::error "💀 $cmd is not a known command"
+	print::info "COMMANDS: $CMDS"
+	print::hr
+	print::bad-exit
 	exit 1
 fi
+
+print::hr
 
 function list {
 	search="$@"
 	if [ -z $search ]; then
-		echo "🗃️ Available Packages:"
-		ls $PKGS
-		exit 0
+		print::info "🗃️ Available Packages:"
+		print::hr
+		print::list $(ls $PKGS)
+		return 0
 	fi
-	echo "🔧 TODO: IMPLEMENT SEARCH FEATURE..."
+	print::error "🔧 TODO: IMPLEMENT SEARCH FEATURE..."
+	return 1
 }
 
 function create {
 	echo "📁 Creating directory → $PKGS/$1"
-	mkcd $PKGS/$1
+	sys::mkdir::cd $PKGS/$1
 	script INSTALL
 }
 
 function add {
 	pkg=$1
 	if ! [ -d $PKGS/$pkg ]; then
-		echo "🫣 Package $pkg does NOT exist."
-		exit 1
+		print::error "🫣 Package $pkg does NOT exist."
+		return 1
 	fi
-	echo "📥 Running INSTALL script for $pkg"
-	echo "⊨======================================="
+	println "📥 Running INSTALL script for $pkg"
+	print::hr =
 	cd $PKGS/$pkg
 	if ./INSTALL; then
-		echo "⊨======================================="
-		echo "✔️  DONE."
+		print::hr =
+		print::ok
 	else
-		echo "⊨======================================="
-		echo "❌ DONE."
+		print::hr x
+		print::error "INSTALL script failed."
+		return 2
 	fi
 }
 
 function remove {
-	echo "🔧 TODO: IMPLENT THE CALL OF UNINSTALL SCRIPT"
+	print::error \
+		"🔧 TODO: IMPLENT THE CALL OF UNINSTALL SCRIPT"
 }
 
 echo "🚀 app $cmd $@"
-$cmd $@
+print::hr
+if $cmd $@; then
+	print::hr
+	print::done
+	exit
+fi
+print::hr
+print::bad-exit $?
+exit 10
diff --git a/bin/ipsum b/bin/ipsum
--- a/bin/ipsum
+++ b/bin/ipsum
@@ -1,29 +1,37 @@
 #!/usr/bin/env bash
 
+source $BASHSTRAP
+include rand
+include print
+
 MODE=$1
 LOWER=$2
 UPPER=$3
 
 if ! [ $MODE ]; then
-	echo "💀 MISSING ARGUMENT."
-	echo
-	echo "USAGE: ipsum <mode> <lower-bound?> <upper-bound?>"
-	echo "  where mode is sentence, paragraph, or page"
+	print::hr
+	print::error "MISSING ARGUMENT"
+	print::hr
+	print::warning "USAGE: ipsum <mode> <min?> <max?>"
+	print::warning "  mode: sentence|paragraph|page"
+	print::hr
 	exit 1
 fi
 
-source ~/includes/rand
-
-if ! [ $UPPER ]; then
+if [ -z $UPPER ]; then
 	UPPER=$LOWER
 fi
 
-if [ $MODE = "sentence" ]; then
-	rand-sentence $LOWER $UPPER
-elif [ $MODE = "paragraph" ]; then
-	rand-paragraph $LOWER $UPPER
-elif [ $MODE = "page "]; then
-	echo "💀 NOT YET IMPLEMENTED"
-fi
-
-
+print::hr +
+case $MODE in
+	sentence)
+		rand::sentence $LOWER $UPPER && printf "\n" ;;
+	paragraph)
+		rand::paragraph $LOWER $UPPER ;;
+	page)
+		print::error "NOT YET IMPLEMENTED" && exit 2;;
+	*)
+		print::error "Mode $MODE does NOT exist." && exit 3 ;;
+esac
+print::hr
+print::done
diff --git a/bin/script b/bin/script
--- a/bin/script
+++ b/bin/script
@@ -1,14 +1,18 @@
 #!/usr/bin/env bash
 
+source $BASHSTRAP
+include print
+
 TYPE=$1
 NAME=$2
 
 if ! [ $TYPE ]; then
-	echo "💀 MISSING ARGUMENT."
-	echo
-	echo "USAGE: script <type?> <name>"
-	echo "  • <type> is any installed interpreter"
-	echo "  • default is 'bash'"
+	print::hr
+	print::error "MISSING ARGUMENT"
+	print::hr
+	print::warning "USAGE: script <type?> <name>"
+	print::warning "  type is any installed interpreter"
+	print::warning "  type default is bash"
 	exit 1
 fi
 
@@ -17,12 +21,16 @@ if ! [ $NAME ]; then
 	TYPE="bash"
 fi
 
-echo "💎 Generating $TYPE script"
-echo "📂 $PWD/$NAME"
+print::hr +
+print::log "💎 Generating $TYPE script"
 
-echo "#!/usr/bin/env $TYPE
-" | cat > $NAME
+if ! echo -e "#!/usr/bin/env $TYPE\n" | cat > $NAME; then
+	print::error "Unable to save -> 📂 $PWD/$NAME"
+	print::bad-exit 2
+	exit 2
+fi
 
 chmod +x $NAME
-
-echo "✔ DONE."
+print::ok "📂 $PWD/$NAME -> 📄 +x $NAME"
+print::hr
+print::done
